Feature/8
ayaka2019436/intern-- pull request #22
Opened 2023-03-28 01:49 UTC by ayaka2019436

## Checklist for Developer
- [x] 最新のdevelopブランチをPullした。Pulled the latest develop branch.
  - できない理由 Reason not to do: 
- [x] Pull RequestをIssueに紐付けた。Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## 📝 そのほかの関連するIssue / Related issues other than connected one

## ⛏ 変更内容 / Details of Changes

- 書籍の情報がない場合は*ngIfを使って「データがありません」 という文言を一覧画面に表示する
## 📸 スクリーンショット / Screenshots

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/123705741/228105884-be6f0ab2-da2f-4ad5-b38e-7c1654c4b1d4.png">

## レビューするポイント (Points for review):

 - 書籍がない場合は「データがありません」と一覧画面に表示されること

2023-03-29 03:26 UTC, x1jy0 requested changes
変数名とかのレビューが多いので、気をつけましょう！

2023-03-29 03:26 UTC, x1jy0 commented on intern-book-app/src/app/components/card/card.component.ts
> +  };
aBookみたいな名前の付け方はかなりの確率で怒られるので別の名前を考えましょう
Delete()とhtmlの方にも合わせて変更してください

2023-03-29 03:26 UTC, x1jy0 commented on intern-book-app/src/app/components/card/card.component.ts
> +  }
関数名も[キャメルケース](https://www.wakuwakubank.com/posts/804-it-naming-convention/#index_id1)に合わせましょう

2023-03-29 03:26 UTC, x1jy0 commented on intern-book-app/src/app/pages/list/list.component.css
> +.Nodeta {
スペルを間違えているので修正してください
CSSファイルの中では[ケバブケース](https://www.wakuwakubank.com/posts/804-it-naming-convention/#index_id4)を使っているので合わせましょう

2023-03-29 03:26 UTC, x1jy0 commented on intern-book-app/src/app/pages/list/list.component.html
> +        />
scoreなのかevaluationなのか統一した方がいいですね

2023-03-29 03:26 UTC, x1jy0 commented on intern-book-app/src/app/pages/list/list.component.html
> +<button (click)="clickTest()">テスト</button> -->
いらないコメントは消しましょう

2023-03-29 03:26 UTC, x1jy0 commented on intern-book-app/src/app/pages/list/list.component.ts
> +  }
"a"とか"b"を使うのは良くないので別な名前を考えましょう

2023-03-29 03:26 UTC, x1jy0 commented on intern-book-app/src/app/pages/list/list.component.ts
>    today: string = '2023/03/22';
もう消してもいいと思います

2023-04-05 07:54 UTC, abe127 approved these changes

2023-04-05 07:54 UTC, merged